/* Generated By:JavaCC: Do not edit this line. APXParserConstants.java */
/*-
 * Copyright (C) 2007 Erik Larsson
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.catacombae.xml.apx;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface APXParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_S = 1;
  /** RegularExpression Id. */
  int CHAR = 2;
  /** RegularExpression Id. */
  int NAME = 3;
  /** RegularExpression Id. */
  int NAMESTART = 4;
  /** RegularExpression Id. */
  int NAMECHAR = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int BASECHAR = 7;
  /** RegularExpression Id. */
  int IDEOGRAPHIC = 8;
  /** RegularExpression Id. */
  int COMBININGCHAR = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int EXTENDER = 11;
  /** RegularExpression Id. */
  int REFERENCE = 12;
  /** RegularExpression Id. */
  int ENTITYREF = 13;
  /** RegularExpression Id. */
  int CHARREF = 14;
  /** RegularExpression Id. */
  int STARTTAG = 16;
  /** RegularExpression Id. */
  int STARTCLOSINGTAG = 17;
  /** RegularExpression Id. */
  int STARTPI = 18;
  /** RegularExpression Id. */
  int STARTXMLDECL = 19;
  /** RegularExpression Id. */
  int STARTDOCTYPEDECL = 20;
  /** RegularExpression Id. */
  int STARTCOMMENT = 21;
  /** RegularExpression Id. */
  int STARTCDATA = 22;
  /** RegularExpression Id. */
  int CHARDATA = 23;
  /** RegularExpression Id. */
  int DEFAULT_REFERENCE = 24;
  /** RegularExpression Id. */
  int ENDXMLDECL = 25;
  /** RegularExpression Id. */
  int XMLDECL_EQ = 26;
  /** RegularExpression Id. */
  int XD_DQUOTE_OPEN = 27;
  /** RegularExpression Id. */
  int XD_SQUOTE_OPEN = 28;
  /** RegularExpression Id. */
  int VERSION = 29;
  /** RegularExpression Id. */
  int ENCODING = 30;
  /** RegularExpression Id. */
  int STANDALONE = 31;
  /** RegularExpression Id. */
  int XD_DQUOTE_STRING = 33;
  /** RegularExpression Id. */
  int XD_DQUOTE_CLOSE = 34;
  /** RegularExpression Id. */
  int XD_SQUOTE_STRING = 35;
  /** RegularExpression Id. */
  int XD_SQUOTE_CLOSE = 36;
  /** RegularExpression Id. */
  int VERSION_DOPEN = 37;
  /** RegularExpression Id. */
  int VERSION_DCLOSE = 38;
  /** RegularExpression Id. */
  int VERSION_SOPEN = 39;
  /** RegularExpression Id. */
  int VERSION_SCLOSE = 40;
  /** RegularExpression Id. */
  int VER = 41;
  /** RegularExpression Id. */
  int STANDALONE_DOPEN = 42;
  /** RegularExpression Id. */
  int STANDALONE_DCLOSE = 43;
  /** RegularExpression Id. */
  int STANDALONE_SOPEN = 44;
  /** RegularExpression Id. */
  int STANDALONE_SCLOSE = 45;
  /** RegularExpression Id. */
  int STANDALONE_YES = 46;
  /** RegularExpression Id. */
  int STANDALONE_NO = 47;
  /** RegularExpression Id. */
  int WDD_NAME = 48;
  /** RegularExpression Id. */
  int ENDDOCTYPEDECL = 49;
  /** RegularExpression Id. */
  int EXTERNALID = 50;
  /** RegularExpression Id. */
  int SYSTEMLITERAL = 51;
  /** RegularExpression Id. */
  int PUBIDLITERAL = 52;
  /** RegularExpression Id. */
  int PUBIDCHAR = 53;
  /** RegularExpression Id. */
  int BEGIN_INTSUBSET = 54;
  /** RegularExpression Id. */
  int END_INTSUBSET = 56;
  /** RegularExpression Id. */
  int WHATEVER = 57;
  /** RegularExpression Id. */
  int ENDCOMMENT = 58;
  /** RegularExpression Id. */
  int COMMENT_ILLEGAL = 59;
  /** RegularExpression Id. */
  int COMMENT_CHAR = 60;
  /** RegularExpression Id. */
  int ENDPI = 61;
  /** RegularExpression Id. */
  int ILLEGALTARGET = 62;
  /** RegularExpression Id. */
  int PITARGET = 63;
  /** RegularExpression Id. */
  int WITHINPI_S = 64;
  /** RegularExpression Id. */
  int PC_CHAR = 65;
  /** RegularExpression Id. */
  int WT_EQ = 66;
  /** RegularExpression Id. */
  int WT_NAME = 67;
  /** RegularExpression Id. */
  int WT_DQUOTE = 68;
  /** RegularExpression Id. */
  int WT_SQUOTE = 69;
  /** RegularExpression Id. */
  int EMPTY_ENDTAG = 70;
  /** RegularExpression Id. */
  int ENDTAG = 71;
  /** RegularExpression Id. */
  int ATTR_DQUOTE = 73;
  /** RegularExpression Id. */
  int ATTR_SQUOTE = 74;
  /** RegularExpression Id. */
  int ATTR_DQUOTE_STRING = 75;
  /** RegularExpression Id. */
  int ATTR_SQUOTE_STRING = 76;
  /** RegularExpression Id. */
  int ATTR_REFERENCE = 77;
  /** RegularExpression Id. */
  int ENDCDATA = 78;
  /** RegularExpression Id. */
  int WCD_CHAR = 79;

  /** Lexical state. */
  int WithinCData = 0;
  /** Lexical state. */
  int Attribute = 1;
  /** Lexical state. */
  int WithinTag = 2;
  /** Lexical state. */
  int WithinPIContent = 3;
  /** Lexical state. */
  int WithinPI = 4;
  /** Lexical state. */
  int Comment = 5;
  /** Lexical state. */
  int WithinIntSubset = 6;
  /** Lexical state. */
  int WithinDoctypeDecl = 7;
  /** Lexical state. */
  int WithinXMLDecl_Standalone = 8;
  /** Lexical state. */
  int WithinXMLDecl_Version = 9;
  /** Lexical state. */
  int WithinXMLDecl_SquoteString = 10;
  /** Lexical state. */
  int WithinXMLDecl_DquoteString = 11;
  /** Lexical state. */
  int WithinXMLDecl = 12;
  /** Lexical state. */
  int DEFAULT = 13;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_S>",
    "<CHAR>",
    "<NAME>",
    "<NAMESTART>",
    "<NAMECHAR>",
    "<LETTER>",
    "<BASECHAR>",
    "<IDEOGRAPHIC>",
    "<COMBININGCHAR>",
    "<DIGIT>",
    "<EXTENDER>",
    "<REFERENCE>",
    "<ENTITYREF>",
    "<CHARREF>",
    "<token of kind 15>",
    "\"<\"",
    "\"</\"",
    "\"<?\"",
    "\"<?xml\"",
    "\"<!DOCTYPE\"",
    "\"<!--\"",
    "\"<![CDATA[\"",
    "<CHARDATA>",
    "<DEFAULT_REFERENCE>",
    "\"?>\"",
    "\"=\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"version\"",
    "\"encoding\"",
    "\"standalone\"",
    "<token of kind 32>",
    "<XD_DQUOTE_STRING>",
    "\"\\\"\"",
    "<XD_SQUOTE_STRING>",
    "\"\\\'\"",
    "\"=\\\"\"",
    "\"\\\"\"",
    "\"=\\\'\"",
    "\"\\\'\"",
    "\"1.0\"",
    "\"=\\\"\"",
    "\"\\\"\"",
    "\"=\\\'\"",
    "\"\\\'\"",
    "\"yes\"",
    "\"no\"",
    "<WDD_NAME>",
    "\">\"",
    "<EXTERNALID>",
    "<SYSTEMLITERAL>",
    "<PUBIDLITERAL>",
    "<PUBIDCHAR>",
    "\"[\"",
    "<token of kind 55>",
    "\"]\"",
    "<WHATEVER>",
    "\"-->\"",
    "\"--\"",
    "<COMMENT_CHAR>",
    "\"?>\"",
    "<ILLEGALTARGET>",
    "<PITARGET>",
    "<WITHINPI_S>",
    "<PC_CHAR>",
    "\"=\"",
    "<WT_NAME>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"/>\"",
    "\">\"",
    "<token of kind 72>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<ATTR_DQUOTE_STRING>",
    "<ATTR_SQUOTE_STRING>",
    "<ATTR_REFERENCE>",
    "\"]]>\"",
    "<WCD_CHAR>",
  };

}
